name: project_news
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  go_router: ^14.2.0
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  talker_dio_logger: ^4.2.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  webview_flutter: ^4.8.0
  intl: ^0.19.0
  firebase_core: ^3.1.1
  firebase_auth: ^4.6.0  # Ganti dengan versi terbaru

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env
